### ISSUE TITLE
Layer data model

### ISSUE THREAD

**Issue by paulRbr** [lbriais/super_stack#2]
Hi Laurent!

Would it be ok to have the possibility to change default Layer's data model?

For now we get a basic `Hash` from https://github.com/lbriais/super_stack/blob/master/lib/super_stack/layer_wrapper.rb#L81
It is quite common in ruby scripts to use either hashes with indifferent access (string or symbol) or even Hashie's `Mash` objects.

What do you think?

**Comment by lbriais** [comment]
For the idea of having a potential other Hash-like "backend", it doesn't sound like a bad idea. I didn't know about the `Mash` class, (I tend to use [OpenStruct](http://ruby-doc.org/stdlib-2.3.0/libdoc/ostruct/rdoc/OpenStruct.html) when I need something with a "dynamic behaviour"), but it's true that the fact it is inheriting from Hash should guaranty that the merge mechanism between layers will work (which is not the case of `OpenStruct`).

Nevertheless you should be able to do the following to directly use `Mash` objects:

``` ruby
mash = Mash.new
# ... do whatever you want with your mash
SuperStack::LayerWrapper.from_hash mash
```

And then your `mash` should be considered as a real layer, which can then be added to the manager.

BTW adding the mash directly to the manager would provide the same result as it is automatically adding the `SuperStack::LayerWrapper` module to any layer added to it (pretty bad practice ^^, especially in the way I check whether or not the module has to be added to the Hash, which is so... java-ish).

Things to do for your potential PR:
- Checking impact on merge mechanism
- Provide a mechanism to define the default `Hash` backend
- Tweak the load mechanism

**Comment by lbriais** [comment]
The point is that Mash structure could easily introduce name clashes with actual methods coming from `SuperStack::LayerWrapper`... So maybe not such a good idea...

**Comment by paulRbr** [comment]
Yes you're right I guess `Mash` is not the best idea. But a `HashWithIndefferentAccess` would be nice. I'll take a look into a potential PR.

Thanks!

**Comment by lbriais** [comment]
Yep at some point I already thought about it, and it would actually make perfectly sense. 
I think I never did it because I didn't like the idea of introducing a dependency on `activesupport` as `super_stack` is a (relatively) "low-level" gem.
Maybe an even more dynamic process that could allow the `HashWithIndefferentAccess` only if existing (ie activesupport required by the project this gem has been added to) but not requiring it as a gem dependency ?
In all cases, choosing it as a user "backend" should be only decided by the user.

All of this leads me to this: Why not using it **only** for the merged hash, while keeping all other layers untouched ? By doing this no need to handle the `load`. The actions to be done would be:
- Add a kind of `Manager` initialization that would check the available "back-ends", defaulting to `[Hash]`.
- Add a new method to the manager to allow to set the `merged_hash_type` (default `Hash`), that would only allow types defined here above.
- Use that type for the `Manager#[](filter=nil)` in order to return the merged result using the selected `merged_hash_type`.

Et voilà... What do you think of that ? It keeps backward compatibility and provides the possibility to extend with any more evolved `Hash` implementation while not introducing extra dependencies.

**Comment by lbriais** [comment]
Of course tests have to pass with both implementations, meaning that `activesupport` may be added as a development dependency only (with ~~potential~~ adaptation)...
